version: 2
updates:
  - directory: /
    assignees:
      - "grikomsn"
    open-pull-requests-limit: 5
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: weekly
    versioning-strategy: lockfile-only
    labels:
      - "dependencies"
