import {
  faDev,
  faDeviantart,
  faDocker,
  faFacebookF,
  faGithub,
  faGitlab,
  faHackerNewsSquare,
  faInstagram,
  faKeybase,
  faLine,
  faMediumM,
  faProductHunt,
  faSoundcloud,
  faSpotify,
  faSteam,
  faTelegram,
  faTwitter,
  faWordpress,
} from '@fortawesome/free-brands-svg-icons'

export default {
  colorHex: '#FEF380',
  email: 'grikomsn@gmail.com',
  emailSecondary: 'griko@protonmail.com',
  links: [
    {
      id: 'dev.to',
      href: 'https://dev.to/grikomsn',
      classFontAwesome: faDev,
      color: '#0a0a0a',
      isPrimary: true,
    },
    {
      id: 'DeviantArt',
      href: 'https://grikomsn.deviantart.com',
      classFontAwesome: faDeviantart,
      color: '#05cc47',
      isPrimary: false,
    },
    {
      id: 'DockerHub',
      href: 'https://hub.docker.com/u/griko',
      classFontAwesome: faDocker,
      color: '#0db7ed',
      isPrimary: false,
    },
    {
      id: 'Facebook',
      href: 'https://fb.me/grikomsn',
      classFontAwesome: faFacebookF,
      color: '#3b5998',
      isPrimary: true,
    },
    {
      id: 'GitHub',
      href: 'https://github.com/grikomsn',
      classFontAwesome: faGithub,
      color: '#25292e',
      isPrimary: true,
    },
    {
      id: 'GitLab',
      href: 'https://gitlab.com/grikomsn',
      classFontAwesome: faGitlab,
      color: '#fa6d34',
      isPrimary: false,
    },
    {
      id: 'Gravatar',
      href: 'https://en.gravatar.com/griko',
      classFontAwesome: faWordpress,
      color: '#1e8cbe',
      isPrimary: false,
    },
    {
      id: 'Hacker News',
      href: 'https://news.ycombinator.com/user?id=griko',
      classFontAwesome: faHackerNewsSquare,
      color: '#ff4000',
      isPrimary: false,
    },
    {
      id: 'Instagram',
      href: 'https://instagram.com/griko_nibras',
      classFontAwesome: faInstagram,
      color: '#e1306c',
      isPrimary: false,
    },
    {
      id: 'Keybase',
      href: 'https://keybase.io/griko',
      classFontAwesome: faKeybase,
      color: '#3ba2fc',
      isPrimary: false,
    },

    {
      id: 'LINE',
      href: 'https://line.me/ti/p/~grikomsn',
      classFontAwesome: faLine,
      color: '#00b900',
      isPrimary: false,
    },

    {
      id: 'Medium',
      href: 'https://medium.com/@griko',
      classFontAwesome: faMediumM,
      color: '#00ab6c',
      isPrimary: false,
    },
    {
      id: 'Product Hunt',
      href: 'https://www.producthunt.com/@griko_nibras',
      classFontAwesome: faProductHunt,
      color: '#da552f',
      isPrimary: false,
    },
    {
      id: 'SoundCloud',
      href: 'https://soundcloud.com/grikomsn',
      classFontAwesome: faSoundcloud,
      color: '#ff7700',
      isPrimary: false,
    },
    {
      id: 'Spotify',
      href: 'https://open.spotify.com/user/grikomsn',
      classFontAwesome: faSpotify,
      color: '#1ed760',
      isPrimary: false,
    },
    {
      id: 'Steam',
      href: 'https://steamcommunity.com/id/grikomsn',
      classFontAwesome: faSteam,
      color: '#171A21',
      isPrimary: false,
    },
    {
      id: 'Telegram',
      href: 'https://t.me/griko_nibras',
      classFontAwesome: faTelegram,
      color: '#0088cc',
      isPrimary: false,
    },
    {
      id: 'Twitter',
      href: 'https://twitter.com/griko_nibras',
      classFontAwesome: faTwitter,
      color: '#1da1f2',
      isPrimary: true,
    },
  ],
  pageTitle: 'Griko Nibras - Software developer from Surabaya, ID',
}
